#!/usr/bin/env python
# -*- coding: utf-8 -*- 

"""
Django settings for useMongo project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import django_mongodb_engine


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c++ogybp9-+!w!e6ay4#qxot&8+g!rhte6h67rwqt8$k5%$maj'

DEBUG = True

ALLOWED_HOSTS = []


import sys

reload(sys)  
sys.setdefaultencoding('utf8')

#!/usr/bin/env python
# -*- coding: utf-8 -*- 

import mongoengine

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fanpages',
    'django_extensions',
    'hamlpy',
    'mongoengine',
    'djangotoolbox',
)

from mongoengine import connect
connect('test')

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'useMongo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates', ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


TEMPLATE_LOADERS = (
    'hamlpy.template.loaders.HamlPyFilesystemLoader',
    'hamlpy.template.loaders.HamlPyAppDirectoriesLoader',   
)

WSGI_APPLICATION = 'useMongo.wsgi.application'




CELERY_MONGODB_SCHEDULER_DB = "celery"
CELERY_MONGODB_SCHEDULER_COLLECTION = "afsdfskaflk"
CELERY_MONGODB_SCHEDULER_URL = "mongodb://root:@mongodb://127.0.0.1:27017"
CELERY_IMPORTS = ['fanpages']

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'


ACCESS_TOKEN = 'EAACEdEose0cBAGxoBUbElnJLRBijcVSFNC5nTiUm0ECTdaZCB74oCs6CJkY8cJHBhyP5xOaiNbVdZBLADGClZABTVOjZCyTAgjaPzDek6wiysvaDyemueCKjFdS09ywZANGdM0yfDD034Q9jnJZAKF7a7LFy7eqZAe9oBXy9MJQPLINLwP7wZCy3cquKTRQRJ4uZBMgZBdRaZAQZBwZDZD'
LIST_WORDS = ["Khuyến mãi", "Giảm giá", "Discount", "Giảm"]

